// AUTO-GENERATED by scripts/gen-content-index.mjs — do not edit by hand.
// Static imports (not fs reads) so Next bundles every content JSON without
// output-file-tracing surprises on the standalone prod build.
import type { TranslatorTexts, FeatureContent } from "@/app/_landing/types";
import chromeEn from "@/app/(en)/texts.json";
import chromeRu from "@/app/ru/texts.json";
import chrome_ar from "./chrome/ar.json";
import chrome_bg from "./chrome/bg.json";
import chrome_ca from "./chrome/ca.json";
import chrome_cs from "./chrome/cs.json";
import chrome_da from "./chrome/da.json";
import chrome_de from "./chrome/de.json";
import chrome_el from "./chrome/el.json";
import chrome_es from "./chrome/es.json";
import chrome_et from "./chrome/et.json";
import chrome_fa from "./chrome/fa.json";
import chrome_fi from "./chrome/fi.json";
import chrome_fr from "./chrome/fr.json";
import chrome_hr from "./chrome/hr.json";
import chrome_hu from "./chrome/hu.json";
import chrome_is from "./chrome/is.json";
import chrome_it from "./chrome/it.json";
import chrome_ja from "./chrome/ja.json";
import chrome_ko from "./chrome/ko.json";
import chrome_lt from "./chrome/lt.json";
import chrome_lv from "./chrome/lv.json";
import chrome_nl from "./chrome/nl.json";
import chrome_no from "./chrome/no.json";
import chrome_pl from "./chrome/pl.json";
import chrome_pt from "./chrome/pt.json";
import chrome_ro from "./chrome/ro.json";
import chrome_sk from "./chrome/sk.json";
import chrome_sl from "./chrome/sl.json";
import chrome_sr from "./chrome/sr.json";
import chrome_sv from "./chrome/sv.json";
import chrome_tr from "./chrome/tr.json";
import chrome_uk from "./chrome/uk.json";
import chrome_zh from "./chrome/zh.json";
import pair_ar_motarjemArabiAlmani from "./pairs/ar/motarjem-arabi-almani.json";
import pair_ar_motarjemArabiFaransi from "./pairs/ar/motarjem-arabi-faransi.json";
import pair_ar_motarjemArabiInjlizi from "./pairs/ar/motarjem-arabi-injlizi.json";
import pair_ar_motarjemArabiIsbani from "./pairs/ar/motarjem-arabi-isbani.json";
import pair_ar_motarjemArabiRusi from "./pairs/ar/motarjem-arabi-rusi.json";
import pair_ar_motarjemArabiTurki from "./pairs/ar/motarjem-arabi-turki.json";
import pair_bg_prevodachBulgarskiAngliyski from "./pairs/bg/prevodach-bulgarski-angliyski.json";
import pair_bg_prevodachBulgarskiNemski from "./pairs/bg/prevodach-bulgarski-nemski.json";
import pair_bg_prevodachBulgarskiRuski from "./pairs/bg/prevodach-bulgarski-ruski.json";
import pair_bg_prevodachBulgarskiTurski from "./pairs/bg/prevodach-bulgarski-turski.json";
import pair_ca_traductorCatalaAngles from "./pairs/ca/traductor-catala-angles.json";
import pair_ca_traductorCatalaCastella from "./pairs/ca/traductor-catala-castella.json";
import pair_ca_traductorCatalaFrances from "./pairs/ca/traductor-catala-frances.json";
import pair_cs_prekladacCeskoAnglicky from "./pairs/cs/prekladac-cesko-anglicky.json";
import pair_cs_prekladacCeskoFrancouzsky from "./pairs/cs/prekladac-cesko-francouzsky.json";
import pair_cs_prekladacCeskoItalsky from "./pairs/cs/prekladac-cesko-italsky.json";
import pair_cs_prekladacCeskoNemecky from "./pairs/cs/prekladac-cesko-nemecky.json";
import pair_cs_prekladacCeskoPolsky from "./pairs/cs/prekladac-cesko-polsky.json";
import pair_cs_prekladacCeskoSlovensky from "./pairs/cs/prekladac-cesko-slovensky.json";
import pair_cs_prekladacCeskoUkrajinsky from "./pairs/cs/prekladac-cesko-ukrajinsky.json";
import pair_da_oversaetterDanskEngelsk from "./pairs/da/oversaetter-dansk-engelsk.json";
import pair_da_oversaetterDanskFransk from "./pairs/da/oversaetter-dansk-fransk.json";
import pair_da_oversaetterDanskSpansk from "./pairs/da/oversaetter-dansk-spansk.json";
import pair_da_oversaetterDanskSvensk from "./pairs/da/oversaetter-dansk-svensk.json";
import pair_da_oversaetterDanskTysk from "./pairs/da/oversaetter-dansk-tysk.json";
import pair_de_uebersetzerDeutschArabisch from "./pairs/de/uebersetzer-deutsch-arabisch.json";
import pair_de_uebersetzerDeutschEnglisch from "./pairs/de/uebersetzer-deutsch-englisch.json";
import pair_de_uebersetzerDeutschItalienisch from "./pairs/de/uebersetzer-deutsch-italienisch.json";
import pair_de_uebersetzerDeutschKroatisch from "./pairs/de/uebersetzer-deutsch-kroatisch.json";
import pair_de_uebersetzerDeutschPolnisch from "./pairs/de/uebersetzer-deutsch-polnisch.json";
import pair_de_uebersetzerDeutschRumaenisch from "./pairs/de/uebersetzer-deutsch-rumaenisch.json";
import pair_de_uebersetzerDeutschRussisch from "./pairs/de/uebersetzer-deutsch-russisch.json";
import pair_de_uebersetzerDeutschSpanisch from "./pairs/de/uebersetzer-deutsch-spanisch.json";
import pair_de_uebersetzerDeutschTuerkisch from "./pairs/de/uebersetzer-deutsch-tuerkisch.json";
import pair_de_uebersetzerDeutschUkrainisch from "./pairs/de/uebersetzer-deutsch-ukrainisch.json";
import pair_el_metafrastisEllinikaAgglika from "./pairs/el/metafrastis-ellinika-agglika.json";
import pair_el_metafrastisEllinikaGallika from "./pairs/el/metafrastis-ellinika-gallika.json";
import pair_el_metafrastisEllinikaGermanika from "./pairs/el/metafrastis-ellinika-germanika.json";
import pair_el_metafrastisEllinikaIspanika from "./pairs/el/metafrastis-ellinika-ispanika.json";
import pair_el_metafrastisEllinikaItalika from "./pairs/el/metafrastis-ellinika-italika.json";
import pair_en_translateArabicToEnglish from "./pairs/en/translate-arabic-to-english.json";
import pair_en_translateChineseToEnglish from "./pairs/en/translate-chinese-to-english.json";
import pair_en_translateEnglishToArabic from "./pairs/en/translate-english-to-arabic.json";
import pair_en_translateEnglishToChinese from "./pairs/en/translate-english-to-chinese.json";
import pair_en_translateEnglishToFrench from "./pairs/en/translate-english-to-french.json";
import pair_en_translateEnglishToGerman from "./pairs/en/translate-english-to-german.json";
import pair_en_translateEnglishToItalian from "./pairs/en/translate-english-to-italian.json";
import pair_en_translateEnglishToJapanese from "./pairs/en/translate-english-to-japanese.json";
import pair_en_translateEnglishToKorean from "./pairs/en/translate-english-to-korean.json";
import pair_en_translateEnglishToPolish from "./pairs/en/translate-english-to-polish.json";
import pair_en_translateEnglishToPortuguese from "./pairs/en/translate-english-to-portuguese.json";
import pair_en_translateEnglishToRussian from "./pairs/en/translate-english-to-russian.json";
import pair_en_translateEnglishToSpanish from "./pairs/en/translate-english-to-spanish.json";
import pair_en_translateEnglishToTurkish from "./pairs/en/translate-english-to-turkish.json";
import pair_en_translateFrenchToEnglish from "./pairs/en/translate-french-to-english.json";
import pair_en_translateGermanToEnglish from "./pairs/en/translate-german-to-english.json";
import pair_en_translateItalianToEnglish from "./pairs/en/translate-italian-to-english.json";
import pair_en_translateJapaneseToEnglish from "./pairs/en/translate-japanese-to-english.json";
import pair_en_translateKoreanToEnglish from "./pairs/en/translate-korean-to-english.json";
import pair_en_translatePolishToEnglish from "./pairs/en/translate-polish-to-english.json";
import pair_en_translatePortugueseToEnglish from "./pairs/en/translate-portuguese-to-english.json";
import pair_en_translateRussianToEnglish from "./pairs/en/translate-russian-to-english.json";
import pair_en_translateSpanishToEnglish from "./pairs/en/translate-spanish-to-english.json";
import pair_en_translateTurkishToEnglish from "./pairs/en/translate-turkish-to-english.json";
import pair_es_traductorEspanolArabe from "./pairs/es/traductor-espanol-arabe.json";
import pair_es_traductorEspanolCatalan from "./pairs/es/traductor-espanol-catalan.json";
import pair_es_traductorEspanolChino from "./pairs/es/traductor-espanol-chino.json";
import pair_es_traductorEspanolFrances from "./pairs/es/traductor-espanol-frances.json";
import pair_es_traductorEspanolIngles from "./pairs/es/traductor-espanol-ingles.json";
import pair_es_traductorEspanolItaliano from "./pairs/es/traductor-espanol-italiano.json";
import pair_es_traductorEspanolPortugues from "./pairs/es/traductor-espanol-portugues.json";
import pair_es_traductorEspanolRuso from "./pairs/es/traductor-espanol-ruso.json";
import pair_et_tolkijaEestiInglise from "./pairs/et/tolkija-eesti-inglise.json";
import pair_et_tolkijaEestiSaksa from "./pairs/et/tolkija-eesti-saksa.json";
import pair_et_tolkijaEestiSoome from "./pairs/et/tolkija-eesti-soome.json";
import pair_fa_motarjemFarsiAlmani from "./pairs/fa/motarjem-farsi-almani.json";
import pair_fa_motarjemFarsiArabi from "./pairs/fa/motarjem-farsi-arabi.json";
import pair_fa_motarjemFarsiEnglisi from "./pairs/fa/motarjem-farsi-englisi.json";
import pair_fa_motarjemFarsiTorki from "./pairs/fa/motarjem-farsi-torki.json";
import pair_fi_kaantajaSuomiEnglanti from "./pairs/fi/kaantaja-suomi-englanti.json";
import pair_fi_kaantajaSuomiEspanja from "./pairs/fi/kaantaja-suomi-espanja.json";
import pair_fi_kaantajaSuomiSaksa from "./pairs/fi/kaantaja-suomi-saksa.json";
import pair_fr_traducteurFrancaisAllemand from "./pairs/fr/traducteur-francais-allemand.json";
import pair_fr_traducteurFrancaisAnglais from "./pairs/fr/traducteur-francais-anglais.json";
import pair_fr_traducteurFrancaisArabe from "./pairs/fr/traducteur-francais-arabe.json";
import pair_fr_traducteurFrancaisEspagnol from "./pairs/fr/traducteur-francais-espagnol.json";
import pair_fr_traducteurFrancaisItalien from "./pairs/fr/traducteur-francais-italien.json";
import pair_fr_traducteurFrancaisNeerlandais from "./pairs/fr/traducteur-francais-neerlandais.json";
import pair_fr_traducteurFrancaisPortugais from "./pairs/fr/traducteur-francais-portugais.json";
import pair_fr_traducteurFrancaisTurc from "./pairs/fr/traducteur-francais-turc.json";
import pair_hr_prevoditeljHrvatskiEngleski from "./pairs/hr/prevoditelj-hrvatski-engleski.json";
import pair_hr_prevoditeljHrvatskiNjemacki from "./pairs/hr/prevoditelj-hrvatski-njemacki.json";
import pair_hr_prevoditeljHrvatskiTalijanski from "./pairs/hr/prevoditelj-hrvatski-talijanski.json";
import pair_hu_forditoMagyarAngol from "./pairs/hu/fordito-magyar-angol.json";
import pair_hu_forditoMagyarNemet from "./pairs/hu/fordito-magyar-nemet.json";
import pair_is_thydandiIslenskuEnska from "./pairs/is/thydandi-islensku-enska.json";
import pair_it_traduttoreItalianoArabo from "./pairs/it/traduttore-italiano-arabo.json";
import pair_it_traduttoreItalianoCinese from "./pairs/it/traduttore-italiano-cinese.json";
import pair_it_traduttoreItalianoFrancese from "./pairs/it/traduttore-italiano-francese.json";
import pair_it_traduttoreItalianoGiapponese from "./pairs/it/traduttore-italiano-giapponese.json";
import pair_it_traduttoreItalianoInglese from "./pairs/it/traduttore-italiano-inglese.json";
import pair_it_traduttoreItalianoRusso from "./pairs/it/traduttore-italiano-russo.json";
import pair_it_traduttoreItalianoTedesco from "./pairs/it/traduttore-italiano-tedesco.json";
import pair_ja_honyakuNihongoChugokugo from "./pairs/ja/honyaku-nihongo-chugokugo.json";
import pair_ja_honyakuNihongoEigo from "./pairs/ja/honyaku-nihongo-eigo.json";
import pair_ja_honyakuNihongoFuransugo from "./pairs/ja/honyaku-nihongo-furansugo.json";
import pair_ja_honyakuNihongoKankokugo from "./pairs/ja/honyaku-nihongo-kankokugo.json";
import pair_ko_beonyeokHangugeoDogileo from "./pairs/ko/beonyeok-hangugeo-dogileo.json";
import pair_ko_beonyeokHangugeoIlboneo from "./pairs/ko/beonyeok-hangugeo-ilboneo.json";
import pair_ko_beonyeokHangugeoJunggugeo from "./pairs/ko/beonyeok-hangugeo-junggugeo.json";
import pair_ko_beonyeokHangugeoYeongeo from "./pairs/ko/beonyeok-hangugeo-yeongeo.json";
import pair_lt_vertejasLietuviuAnglu from "./pairs/lt/vertejas-lietuviu-anglu.json";
import pair_lt_vertejasLietuviuLenku from "./pairs/lt/vertejas-lietuviu-lenku.json";
import pair_lt_vertejasLietuviuVokieciu from "./pairs/lt/vertejas-lietuviu-vokieciu.json";
import pair_lv_tulkotajsLatviesuAnglu from "./pairs/lv/tulkotajs-latviesu-anglu.json";
import pair_lv_tulkotajsLatviesuKrievu from "./pairs/lv/tulkotajs-latviesu-krievu.json";
import pair_nl_vertalerNederlandsDuits from "./pairs/nl/vertaler-nederlands-duits.json";
import pair_nl_vertalerNederlandsEngels from "./pairs/nl/vertaler-nederlands-engels.json";
import pair_nl_vertalerNederlandsFrans from "./pairs/nl/vertaler-nederlands-frans.json";
import pair_nl_vertalerNederlandsItaliaans from "./pairs/nl/vertaler-nederlands-italiaans.json";
import pair_nl_vertalerNederlandsSpaans from "./pairs/nl/vertaler-nederlands-spaans.json";
import pair_nl_vertalerNederlandsTurks from "./pairs/nl/vertaler-nederlands-turks.json";
import pair_no_oversetterNorskEngelsk from "./pairs/no/oversetter-norsk-engelsk.json";
import pair_no_oversetterNorskSpansk from "./pairs/no/oversetter-norsk-spansk.json";
import pair_no_oversetterNorskSvensk from "./pairs/no/oversetter-norsk-svensk.json";
import pair_no_oversetterNorskTysk from "./pairs/no/oversetter-norsk-tysk.json";
import pair_pl_tlumaczPolskoAngielski from "./pairs/pl/tlumacz-polsko-angielski.json";
import pair_pl_tlumaczPolskoChinski from "./pairs/pl/tlumacz-polsko-chinski.json";
import pair_pl_tlumaczPolskoCzeski from "./pairs/pl/tlumacz-polsko-czeski.json";
import pair_pl_tlumaczPolskoFrancuski from "./pairs/pl/tlumacz-polsko-francuski.json";
import pair_pl_tlumaczPolskoHiszpanski from "./pairs/pl/tlumacz-polsko-hiszpanski.json";
import pair_pl_tlumaczPolskoNiemiecki from "./pairs/pl/tlumacz-polsko-niemiecki.json";
import pair_pl_tlumaczPolskoRosyjski from "./pairs/pl/tlumacz-polsko-rosyjski.json";
import pair_pl_tlumaczPolskoUkrainski from "./pairs/pl/tlumacz-polsko-ukrainski.json";
import pair_pt_tradutorPortuguesArabe from "./pairs/pt/tradutor-portugues-arabe.json";
import pair_pt_tradutorPortuguesEspanhol from "./pairs/pt/tradutor-portugues-espanhol.json";
import pair_pt_tradutorPortuguesFrances from "./pairs/pt/tradutor-portugues-frances.json";
import pair_pt_tradutorPortuguesIngles from "./pairs/pt/tradutor-portugues-ingles.json";
import pair_pt_tradutorPortuguesItaliano from "./pairs/pt/tradutor-portugues-italiano.json";
import pair_pt_tradutorPortuguesJapones from "./pairs/pt/tradutor-portugues-japones.json";
import pair_ro_traducereRomanaEngleza from "./pairs/ro/traducere-romana-engleza.json";
import pair_ro_traducereRomanaFranceza from "./pairs/ro/traducere-romana-franceza.json";
import pair_ro_traducereRomanaGermana from "./pairs/ro/traducere-romana-germana.json";
import pair_ro_traducereRomanaItaliana from "./pairs/ro/traducere-romana-italiana.json";
import pair_ro_traducereRomanaSpaniola from "./pairs/ro/traducere-romana-spaniola.json";
import pair_ro_traducereRomanaTurca from "./pairs/ro/traducere-romana-turca.json";
import pair_ru_perevodchikSRusskogoNaAngliyskiy from "./pairs/ru/perevodchik-s-russkogo-na-angliyskiy.json";
import pair_ru_perevodchikSRusskogoNaArabskiy from "./pairs/ru/perevodchik-s-russkogo-na-arabskiy.json";
import pair_ru_perevodchikSRusskogoNaIspanskiy from "./pairs/ru/perevodchik-s-russkogo-na-ispanskiy.json";
import pair_ru_perevodchikSRusskogoNaNemetskiy from "./pairs/ru/perevodchik-s-russkogo-na-nemetskiy.json";
import pair_ru_perevodchikSRusskogoNaPolskiy from "./pairs/ru/perevodchik-s-russkogo-na-polskiy.json";
import pair_ru_perevodchikSRusskogoNaTuretskiy from "./pairs/ru/perevodchik-s-russkogo-na-turetskiy.json";
import pair_ru_perevodchikSRusskogoNaUkrainskiy from "./pairs/ru/perevodchik-s-russkogo-na-ukrainskiy.json";
import pair_sk_prekladacSlovenskoAnglicky from "./pairs/sk/prekladac-slovensko-anglicky.json";
import pair_sk_prekladacSlovenskoCesky from "./pairs/sk/prekladac-slovensko-cesky.json";
import pair_sk_prekladacSlovenskoNemecky from "./pairs/sk/prekladac-slovensko-nemecky.json";
import pair_sl_prevajalnikSlovenskoAnglesko from "./pairs/sl/prevajalnik-slovensko-anglesko.json";
import pair_sl_prevajalnikSlovenskoItalijansko from "./pairs/sl/prevajalnik-slovensko-italijansko.json";
import pair_sl_prevajalnikSlovenskoNemsko from "./pairs/sl/prevajalnik-slovensko-nemsko.json";
import pair_sr_prevodilacSrpskiEngleski from "./pairs/sr/prevodilac-srpski-engleski.json";
import pair_sr_prevodilacSrpskiItalijanski from "./pairs/sr/prevodilac-srpski-italijanski.json";
import pair_sr_prevodilacSrpskiNemacki from "./pairs/sr/prevodilac-srpski-nemacki.json";
import pair_sr_prevodilacSrpskiRuski from "./pairs/sr/prevodilac-srpski-ruski.json";
import pair_sr_prevodilacSrpskiSpanski from "./pairs/sr/prevodilac-srpski-spanski.json";
import pair_sr_prevodilacSrpskiTurski from "./pairs/sr/prevodilac-srpski-turski.json";
import pair_sv_oversattareSvenskaDanska from "./pairs/sv/oversattare-svenska-danska.json";
import pair_sv_oversattareSvenskaEngelska from "./pairs/sv/oversattare-svenska-engelska.json";
import pair_sv_oversattareSvenskaFinska from "./pairs/sv/oversattare-svenska-finska.json";
import pair_sv_oversattareSvenskaFranska from "./pairs/sv/oversattare-svenska-franska.json";
import pair_sv_oversattareSvenskaNorska from "./pairs/sv/oversattare-svenska-norska.json";
import pair_sv_oversattareSvenskaSpanska from "./pairs/sv/oversattare-svenska-spanska.json";
import pair_sv_oversattareSvenskaTyska from "./pairs/sv/oversattare-svenska-tyska.json";
import pair_tr_ceviriTurkceAlmanca from "./pairs/tr/ceviri-turkce-almanca.json";
import pair_tr_ceviriTurkceArapca from "./pairs/tr/ceviri-turkce-arapca.json";
import pair_tr_ceviriTurkceFarsca from "./pairs/tr/ceviri-turkce-farsca.json";
import pair_tr_ceviriTurkceFransizca from "./pairs/tr/ceviri-turkce-fransizca.json";
import pair_tr_ceviriTurkceIngilizce from "./pairs/tr/ceviri-turkce-ingilizce.json";
import pair_tr_ceviriTurkceIspanyolca from "./pairs/tr/ceviri-turkce-ispanyolca.json";
import pair_tr_ceviriTurkceRusca from "./pairs/tr/ceviri-turkce-rusca.json";
import pair_uk_perekladachZUkrainskoiNaAnhliysku from "./pairs/uk/perekladach-z-ukrainskoi-na-anhliysku.json";
import pair_uk_perekladachZUkrainskoiNaChesku from "./pairs/uk/perekladach-z-ukrainskoi-na-chesku.json";
import pair_uk_perekladachZUkrainskoiNaIspansku from "./pairs/uk/perekladach-z-ukrainskoi-na-ispansku.json";
import pair_uk_perekladachZUkrainskoiNaItaliysku from "./pairs/uk/perekladach-z-ukrainskoi-na-italiysku.json";
import pair_uk_perekladachZUkrainskoiNaNimetsku from "./pairs/uk/perekladach-z-ukrainskoi-na-nimetsku.json";
import pair_uk_perekladachZUkrainskoiNaPolsku from "./pairs/uk/perekladach-z-ukrainskoi-na-polsku.json";
import pair_uk_perekladachZUkrainskoiNaRosiysku from "./pairs/uk/perekladach-z-ukrainskoi-na-rosiysku.json";
import pair_zh_fanyiZhongwenEwen from "./pairs/zh/fanyi-zhongwen-ewen.json";
import pair_zh_fanyiZhongwenRiwen from "./pairs/zh/fanyi-zhongwen-riwen.json";
import pair_zh_fanyiZhongwenYingwen from "./pairs/zh/fanyi-zhongwen-yingwen.json";

// Chrome (header/footer/translator widget + home copy) per locale. en/ru live
// with their static routes; generated locales live in content/chrome/.
export const CHROME: Record<string, TranslatorTexts> = {
  en: chromeEn as TranslatorTexts,
  ru: chromeRu as TranslatorTexts,
  "ar": chrome_ar as unknown as TranslatorTexts,
  "bg": chrome_bg as unknown as TranslatorTexts,
  "ca": chrome_ca as unknown as TranslatorTexts,
  "cs": chrome_cs as unknown as TranslatorTexts,
  "da": chrome_da as unknown as TranslatorTexts,
  "de": chrome_de as unknown as TranslatorTexts,
  "el": chrome_el as unknown as TranslatorTexts,
  "es": chrome_es as unknown as TranslatorTexts,
  "et": chrome_et as unknown as TranslatorTexts,
  "fa": chrome_fa as unknown as TranslatorTexts,
  "fi": chrome_fi as unknown as TranslatorTexts,
  "fr": chrome_fr as unknown as TranslatorTexts,
  "hr": chrome_hr as unknown as TranslatorTexts,
  "hu": chrome_hu as unknown as TranslatorTexts,
  "is": chrome_is as unknown as TranslatorTexts,
  "it": chrome_it as unknown as TranslatorTexts,
  "ja": chrome_ja as unknown as TranslatorTexts,
  "ko": chrome_ko as unknown as TranslatorTexts,
  "lt": chrome_lt as unknown as TranslatorTexts,
  "lv": chrome_lv as unknown as TranslatorTexts,
  "nl": chrome_nl as unknown as TranslatorTexts,
  "no": chrome_no as unknown as TranslatorTexts,
  "pl": chrome_pl as unknown as TranslatorTexts,
  "pt": chrome_pt as unknown as TranslatorTexts,
  "ro": chrome_ro as unknown as TranslatorTexts,
  "sk": chrome_sk as unknown as TranslatorTexts,
  "sl": chrome_sl as unknown as TranslatorTexts,
  "sr": chrome_sr as unknown as TranslatorTexts,
  "sv": chrome_sv as unknown as TranslatorTexts,
  "tr": chrome_tr as unknown as TranslatorTexts,
  "uk": chrome_uk as unknown as TranslatorTexts,
  "zh": chrome_zh as unknown as TranslatorTexts,
};

// Pair-page content keyed by `${locale}/${slug}`.
export const PAIR_CONTENT: Record<string, FeatureContent> = {
  "ar/motarjem-arabi-almani": pair_ar_motarjemArabiAlmani as unknown as FeatureContent,
  "ar/motarjem-arabi-faransi": pair_ar_motarjemArabiFaransi as unknown as FeatureContent,
  "ar/motarjem-arabi-injlizi": pair_ar_motarjemArabiInjlizi as unknown as FeatureContent,
  "ar/motarjem-arabi-isbani": pair_ar_motarjemArabiIsbani as unknown as FeatureContent,
  "ar/motarjem-arabi-rusi": pair_ar_motarjemArabiRusi as unknown as FeatureContent,
  "ar/motarjem-arabi-turki": pair_ar_motarjemArabiTurki as unknown as FeatureContent,
  "bg/prevodach-bulgarski-angliyski": pair_bg_prevodachBulgarskiAngliyski as unknown as FeatureContent,
  "bg/prevodach-bulgarski-nemski": pair_bg_prevodachBulgarskiNemski as unknown as FeatureContent,
  "bg/prevodach-bulgarski-ruski": pair_bg_prevodachBulgarskiRuski as unknown as FeatureContent,
  "bg/prevodach-bulgarski-turski": pair_bg_prevodachBulgarskiTurski as unknown as FeatureContent,
  "ca/traductor-catala-angles": pair_ca_traductorCatalaAngles as unknown as FeatureContent,
  "ca/traductor-catala-castella": pair_ca_traductorCatalaCastella as unknown as FeatureContent,
  "ca/traductor-catala-frances": pair_ca_traductorCatalaFrances as unknown as FeatureContent,
  "cs/prekladac-cesko-anglicky": pair_cs_prekladacCeskoAnglicky as unknown as FeatureContent,
  "cs/prekladac-cesko-francouzsky": pair_cs_prekladacCeskoFrancouzsky as unknown as FeatureContent,
  "cs/prekladac-cesko-italsky": pair_cs_prekladacCeskoItalsky as unknown as FeatureContent,
  "cs/prekladac-cesko-nemecky": pair_cs_prekladacCeskoNemecky as unknown as FeatureContent,
  "cs/prekladac-cesko-polsky": pair_cs_prekladacCeskoPolsky as unknown as FeatureContent,
  "cs/prekladac-cesko-slovensky": pair_cs_prekladacCeskoSlovensky as unknown as FeatureContent,
  "cs/prekladac-cesko-ukrajinsky": pair_cs_prekladacCeskoUkrajinsky as unknown as FeatureContent,
  "da/oversaetter-dansk-engelsk": pair_da_oversaetterDanskEngelsk as unknown as FeatureContent,
  "da/oversaetter-dansk-fransk": pair_da_oversaetterDanskFransk as unknown as FeatureContent,
  "da/oversaetter-dansk-spansk": pair_da_oversaetterDanskSpansk as unknown as FeatureContent,
  "da/oversaetter-dansk-svensk": pair_da_oversaetterDanskSvensk as unknown as FeatureContent,
  "da/oversaetter-dansk-tysk": pair_da_oversaetterDanskTysk as unknown as FeatureContent,
  "de/uebersetzer-deutsch-arabisch": pair_de_uebersetzerDeutschArabisch as unknown as FeatureContent,
  "de/uebersetzer-deutsch-englisch": pair_de_uebersetzerDeutschEnglisch as unknown as FeatureContent,
  "de/uebersetzer-deutsch-italienisch": pair_de_uebersetzerDeutschItalienisch as unknown as FeatureContent,
  "de/uebersetzer-deutsch-kroatisch": pair_de_uebersetzerDeutschKroatisch as unknown as FeatureContent,
  "de/uebersetzer-deutsch-polnisch": pair_de_uebersetzerDeutschPolnisch as unknown as FeatureContent,
  "de/uebersetzer-deutsch-rumaenisch": pair_de_uebersetzerDeutschRumaenisch as unknown as FeatureContent,
  "de/uebersetzer-deutsch-russisch": pair_de_uebersetzerDeutschRussisch as unknown as FeatureContent,
  "de/uebersetzer-deutsch-spanisch": pair_de_uebersetzerDeutschSpanisch as unknown as FeatureContent,
  "de/uebersetzer-deutsch-tuerkisch": pair_de_uebersetzerDeutschTuerkisch as unknown as FeatureContent,
  "de/uebersetzer-deutsch-ukrainisch": pair_de_uebersetzerDeutschUkrainisch as unknown as FeatureContent,
  "el/metafrastis-ellinika-agglika": pair_el_metafrastisEllinikaAgglika as unknown as FeatureContent,
  "el/metafrastis-ellinika-gallika": pair_el_metafrastisEllinikaGallika as unknown as FeatureContent,
  "el/metafrastis-ellinika-germanika": pair_el_metafrastisEllinikaGermanika as unknown as FeatureContent,
  "el/metafrastis-ellinika-ispanika": pair_el_metafrastisEllinikaIspanika as unknown as FeatureContent,
  "el/metafrastis-ellinika-italika": pair_el_metafrastisEllinikaItalika as unknown as FeatureContent,
  "en/translate-arabic-to-english": pair_en_translateArabicToEnglish as unknown as FeatureContent,
  "en/translate-chinese-to-english": pair_en_translateChineseToEnglish as unknown as FeatureContent,
  "en/translate-english-to-arabic": pair_en_translateEnglishToArabic as unknown as FeatureContent,
  "en/translate-english-to-chinese": pair_en_translateEnglishToChinese as unknown as FeatureContent,
  "en/translate-english-to-french": pair_en_translateEnglishToFrench as unknown as FeatureContent,
  "en/translate-english-to-german": pair_en_translateEnglishToGerman as unknown as FeatureContent,
  "en/translate-english-to-italian": pair_en_translateEnglishToItalian as unknown as FeatureContent,
  "en/translate-english-to-japanese": pair_en_translateEnglishToJapanese as unknown as FeatureContent,
  "en/translate-english-to-korean": pair_en_translateEnglishToKorean as unknown as FeatureContent,
  "en/translate-english-to-polish": pair_en_translateEnglishToPolish as unknown as FeatureContent,
  "en/translate-english-to-portuguese": pair_en_translateEnglishToPortuguese as unknown as FeatureContent,
  "en/translate-english-to-russian": pair_en_translateEnglishToRussian as unknown as FeatureContent,
  "en/translate-english-to-spanish": pair_en_translateEnglishToSpanish as unknown as FeatureContent,
  "en/translate-english-to-turkish": pair_en_translateEnglishToTurkish as unknown as FeatureContent,
  "en/translate-french-to-english": pair_en_translateFrenchToEnglish as unknown as FeatureContent,
  "en/translate-german-to-english": pair_en_translateGermanToEnglish as unknown as FeatureContent,
  "en/translate-italian-to-english": pair_en_translateItalianToEnglish as unknown as FeatureContent,
  "en/translate-japanese-to-english": pair_en_translateJapaneseToEnglish as unknown as FeatureContent,
  "en/translate-korean-to-english": pair_en_translateKoreanToEnglish as unknown as FeatureContent,
  "en/translate-polish-to-english": pair_en_translatePolishToEnglish as unknown as FeatureContent,
  "en/translate-portuguese-to-english": pair_en_translatePortugueseToEnglish as unknown as FeatureContent,
  "en/translate-russian-to-english": pair_en_translateRussianToEnglish as unknown as FeatureContent,
  "en/translate-spanish-to-english": pair_en_translateSpanishToEnglish as unknown as FeatureContent,
  "en/translate-turkish-to-english": pair_en_translateTurkishToEnglish as unknown as FeatureContent,
  "es/traductor-espanol-arabe": pair_es_traductorEspanolArabe as unknown as FeatureContent,
  "es/traductor-espanol-catalan": pair_es_traductorEspanolCatalan as unknown as FeatureContent,
  "es/traductor-espanol-chino": pair_es_traductorEspanolChino as unknown as FeatureContent,
  "es/traductor-espanol-frances": pair_es_traductorEspanolFrances as unknown as FeatureContent,
  "es/traductor-espanol-ingles": pair_es_traductorEspanolIngles as unknown as FeatureContent,
  "es/traductor-espanol-italiano": pair_es_traductorEspanolItaliano as unknown as FeatureContent,
  "es/traductor-espanol-portugues": pair_es_traductorEspanolPortugues as unknown as FeatureContent,
  "es/traductor-espanol-ruso": pair_es_traductorEspanolRuso as unknown as FeatureContent,
  "et/tolkija-eesti-inglise": pair_et_tolkijaEestiInglise as unknown as FeatureContent,
  "et/tolkija-eesti-saksa": pair_et_tolkijaEestiSaksa as unknown as FeatureContent,
  "et/tolkija-eesti-soome": pair_et_tolkijaEestiSoome as unknown as FeatureContent,
  "fa/motarjem-farsi-almani": pair_fa_motarjemFarsiAlmani as unknown as FeatureContent,
  "fa/motarjem-farsi-arabi": pair_fa_motarjemFarsiArabi as unknown as FeatureContent,
  "fa/motarjem-farsi-englisi": pair_fa_motarjemFarsiEnglisi as unknown as FeatureContent,
  "fa/motarjem-farsi-torki": pair_fa_motarjemFarsiTorki as unknown as FeatureContent,
  "fi/kaantaja-suomi-englanti": pair_fi_kaantajaSuomiEnglanti as unknown as FeatureContent,
  "fi/kaantaja-suomi-espanja": pair_fi_kaantajaSuomiEspanja as unknown as FeatureContent,
  "fi/kaantaja-suomi-saksa": pair_fi_kaantajaSuomiSaksa as unknown as FeatureContent,
  "fr/traducteur-francais-allemand": pair_fr_traducteurFrancaisAllemand as unknown as FeatureContent,
  "fr/traducteur-francais-anglais": pair_fr_traducteurFrancaisAnglais as unknown as FeatureContent,
  "fr/traducteur-francais-arabe": pair_fr_traducteurFrancaisArabe as unknown as FeatureContent,
  "fr/traducteur-francais-espagnol": pair_fr_traducteurFrancaisEspagnol as unknown as FeatureContent,
  "fr/traducteur-francais-italien": pair_fr_traducteurFrancaisItalien as unknown as FeatureContent,
  "fr/traducteur-francais-neerlandais": pair_fr_traducteurFrancaisNeerlandais as unknown as FeatureContent,
  "fr/traducteur-francais-portugais": pair_fr_traducteurFrancaisPortugais as unknown as FeatureContent,
  "fr/traducteur-francais-turc": pair_fr_traducteurFrancaisTurc as unknown as FeatureContent,
  "hr/prevoditelj-hrvatski-engleski": pair_hr_prevoditeljHrvatskiEngleski as unknown as FeatureContent,
  "hr/prevoditelj-hrvatski-njemacki": pair_hr_prevoditeljHrvatskiNjemacki as unknown as FeatureContent,
  "hr/prevoditelj-hrvatski-talijanski": pair_hr_prevoditeljHrvatskiTalijanski as unknown as FeatureContent,
  "hu/fordito-magyar-angol": pair_hu_forditoMagyarAngol as unknown as FeatureContent,
  "hu/fordito-magyar-nemet": pair_hu_forditoMagyarNemet as unknown as FeatureContent,
  "is/thydandi-islensku-enska": pair_is_thydandiIslenskuEnska as unknown as FeatureContent,
  "it/traduttore-italiano-arabo": pair_it_traduttoreItalianoArabo as unknown as FeatureContent,
  "it/traduttore-italiano-cinese": pair_it_traduttoreItalianoCinese as unknown as FeatureContent,
  "it/traduttore-italiano-francese": pair_it_traduttoreItalianoFrancese as unknown as FeatureContent,
  "it/traduttore-italiano-giapponese": pair_it_traduttoreItalianoGiapponese as unknown as FeatureContent,
  "it/traduttore-italiano-inglese": pair_it_traduttoreItalianoInglese as unknown as FeatureContent,
  "it/traduttore-italiano-russo": pair_it_traduttoreItalianoRusso as unknown as FeatureContent,
  "it/traduttore-italiano-tedesco": pair_it_traduttoreItalianoTedesco as unknown as FeatureContent,
  "ja/honyaku-nihongo-chugokugo": pair_ja_honyakuNihongoChugokugo as unknown as FeatureContent,
  "ja/honyaku-nihongo-eigo": pair_ja_honyakuNihongoEigo as unknown as FeatureContent,
  "ja/honyaku-nihongo-furansugo": pair_ja_honyakuNihongoFuransugo as unknown as FeatureContent,
  "ja/honyaku-nihongo-kankokugo": pair_ja_honyakuNihongoKankokugo as unknown as FeatureContent,
  "ko/beonyeok-hangugeo-dogileo": pair_ko_beonyeokHangugeoDogileo as unknown as FeatureContent,
  "ko/beonyeok-hangugeo-ilboneo": pair_ko_beonyeokHangugeoIlboneo as unknown as FeatureContent,
  "ko/beonyeok-hangugeo-junggugeo": pair_ko_beonyeokHangugeoJunggugeo as unknown as FeatureContent,
  "ko/beonyeok-hangugeo-yeongeo": pair_ko_beonyeokHangugeoYeongeo as unknown as FeatureContent,
  "lt/vertejas-lietuviu-anglu": pair_lt_vertejasLietuviuAnglu as unknown as FeatureContent,
  "lt/vertejas-lietuviu-lenku": pair_lt_vertejasLietuviuLenku as unknown as FeatureContent,
  "lt/vertejas-lietuviu-vokieciu": pair_lt_vertejasLietuviuVokieciu as unknown as FeatureContent,
  "lv/tulkotajs-latviesu-anglu": pair_lv_tulkotajsLatviesuAnglu as unknown as FeatureContent,
  "lv/tulkotajs-latviesu-krievu": pair_lv_tulkotajsLatviesuKrievu as unknown as FeatureContent,
  "nl/vertaler-nederlands-duits": pair_nl_vertalerNederlandsDuits as unknown as FeatureContent,
  "nl/vertaler-nederlands-engels": pair_nl_vertalerNederlandsEngels as unknown as FeatureContent,
  "nl/vertaler-nederlands-frans": pair_nl_vertalerNederlandsFrans as unknown as FeatureContent,
  "nl/vertaler-nederlands-italiaans": pair_nl_vertalerNederlandsItaliaans as unknown as FeatureContent,
  "nl/vertaler-nederlands-spaans": pair_nl_vertalerNederlandsSpaans as unknown as FeatureContent,
  "nl/vertaler-nederlands-turks": pair_nl_vertalerNederlandsTurks as unknown as FeatureContent,
  "no/oversetter-norsk-engelsk": pair_no_oversetterNorskEngelsk as unknown as FeatureContent,
  "no/oversetter-norsk-spansk": pair_no_oversetterNorskSpansk as unknown as FeatureContent,
  "no/oversetter-norsk-svensk": pair_no_oversetterNorskSvensk as unknown as FeatureContent,
  "no/oversetter-norsk-tysk": pair_no_oversetterNorskTysk as unknown as FeatureContent,
  "pl/tlumacz-polsko-angielski": pair_pl_tlumaczPolskoAngielski as unknown as FeatureContent,
  "pl/tlumacz-polsko-chinski": pair_pl_tlumaczPolskoChinski as unknown as FeatureContent,
  "pl/tlumacz-polsko-czeski": pair_pl_tlumaczPolskoCzeski as unknown as FeatureContent,
  "pl/tlumacz-polsko-francuski": pair_pl_tlumaczPolskoFrancuski as unknown as FeatureContent,
  "pl/tlumacz-polsko-hiszpanski": pair_pl_tlumaczPolskoHiszpanski as unknown as FeatureContent,
  "pl/tlumacz-polsko-niemiecki": pair_pl_tlumaczPolskoNiemiecki as unknown as FeatureContent,
  "pl/tlumacz-polsko-rosyjski": pair_pl_tlumaczPolskoRosyjski as unknown as FeatureContent,
  "pl/tlumacz-polsko-ukrainski": pair_pl_tlumaczPolskoUkrainski as unknown as FeatureContent,
  "pt/tradutor-portugues-arabe": pair_pt_tradutorPortuguesArabe as unknown as FeatureContent,
  "pt/tradutor-portugues-espanhol": pair_pt_tradutorPortuguesEspanhol as unknown as FeatureContent,
  "pt/tradutor-portugues-frances": pair_pt_tradutorPortuguesFrances as unknown as FeatureContent,
  "pt/tradutor-portugues-ingles": pair_pt_tradutorPortuguesIngles as unknown as FeatureContent,
  "pt/tradutor-portugues-italiano": pair_pt_tradutorPortuguesItaliano as unknown as FeatureContent,
  "pt/tradutor-portugues-japones": pair_pt_tradutorPortuguesJapones as unknown as FeatureContent,
  "ro/traducere-romana-engleza": pair_ro_traducereRomanaEngleza as unknown as FeatureContent,
  "ro/traducere-romana-franceza": pair_ro_traducereRomanaFranceza as unknown as FeatureContent,
  "ro/traducere-romana-germana": pair_ro_traducereRomanaGermana as unknown as FeatureContent,
  "ro/traducere-romana-italiana": pair_ro_traducereRomanaItaliana as unknown as FeatureContent,
  "ro/traducere-romana-spaniola": pair_ro_traducereRomanaSpaniola as unknown as FeatureContent,
  "ro/traducere-romana-turca": pair_ro_traducereRomanaTurca as unknown as FeatureContent,
  "ru/perevodchik-s-russkogo-na-angliyskiy": pair_ru_perevodchikSRusskogoNaAngliyskiy as unknown as FeatureContent,
  "ru/perevodchik-s-russkogo-na-arabskiy": pair_ru_perevodchikSRusskogoNaArabskiy as unknown as FeatureContent,
  "ru/perevodchik-s-russkogo-na-ispanskiy": pair_ru_perevodchikSRusskogoNaIspanskiy as unknown as FeatureContent,
  "ru/perevodchik-s-russkogo-na-nemetskiy": pair_ru_perevodchikSRusskogoNaNemetskiy as unknown as FeatureContent,
  "ru/perevodchik-s-russkogo-na-polskiy": pair_ru_perevodchikSRusskogoNaPolskiy as unknown as FeatureContent,
  "ru/perevodchik-s-russkogo-na-turetskiy": pair_ru_perevodchikSRusskogoNaTuretskiy as unknown as FeatureContent,
  "ru/perevodchik-s-russkogo-na-ukrainskiy": pair_ru_perevodchikSRusskogoNaUkrainskiy as unknown as FeatureContent,
  "sk/prekladac-slovensko-anglicky": pair_sk_prekladacSlovenskoAnglicky as unknown as FeatureContent,
  "sk/prekladac-slovensko-cesky": pair_sk_prekladacSlovenskoCesky as unknown as FeatureContent,
  "sk/prekladac-slovensko-nemecky": pair_sk_prekladacSlovenskoNemecky as unknown as FeatureContent,
  "sl/prevajalnik-slovensko-anglesko": pair_sl_prevajalnikSlovenskoAnglesko as unknown as FeatureContent,
  "sl/prevajalnik-slovensko-italijansko": pair_sl_prevajalnikSlovenskoItalijansko as unknown as FeatureContent,
  "sl/prevajalnik-slovensko-nemsko": pair_sl_prevajalnikSlovenskoNemsko as unknown as FeatureContent,
  "sr/prevodilac-srpski-engleski": pair_sr_prevodilacSrpskiEngleski as unknown as FeatureContent,
  "sr/prevodilac-srpski-italijanski": pair_sr_prevodilacSrpskiItalijanski as unknown as FeatureContent,
  "sr/prevodilac-srpski-nemacki": pair_sr_prevodilacSrpskiNemacki as unknown as FeatureContent,
  "sr/prevodilac-srpski-ruski": pair_sr_prevodilacSrpskiRuski as unknown as FeatureContent,
  "sr/prevodilac-srpski-spanski": pair_sr_prevodilacSrpskiSpanski as unknown as FeatureContent,
  "sr/prevodilac-srpski-turski": pair_sr_prevodilacSrpskiTurski as unknown as FeatureContent,
  "sv/oversattare-svenska-danska": pair_sv_oversattareSvenskaDanska as unknown as FeatureContent,
  "sv/oversattare-svenska-engelska": pair_sv_oversattareSvenskaEngelska as unknown as FeatureContent,
  "sv/oversattare-svenska-finska": pair_sv_oversattareSvenskaFinska as unknown as FeatureContent,
  "sv/oversattare-svenska-franska": pair_sv_oversattareSvenskaFranska as unknown as FeatureContent,
  "sv/oversattare-svenska-norska": pair_sv_oversattareSvenskaNorska as unknown as FeatureContent,
  "sv/oversattare-svenska-spanska": pair_sv_oversattareSvenskaSpanska as unknown as FeatureContent,
  "sv/oversattare-svenska-tyska": pair_sv_oversattareSvenskaTyska as unknown as FeatureContent,
  "tr/ceviri-turkce-almanca": pair_tr_ceviriTurkceAlmanca as unknown as FeatureContent,
  "tr/ceviri-turkce-arapca": pair_tr_ceviriTurkceArapca as unknown as FeatureContent,
  "tr/ceviri-turkce-farsca": pair_tr_ceviriTurkceFarsca as unknown as FeatureContent,
  "tr/ceviri-turkce-fransizca": pair_tr_ceviriTurkceFransizca as unknown as FeatureContent,
  "tr/ceviri-turkce-ingilizce": pair_tr_ceviriTurkceIngilizce as unknown as FeatureContent,
  "tr/ceviri-turkce-ispanyolca": pair_tr_ceviriTurkceIspanyolca as unknown as FeatureContent,
  "tr/ceviri-turkce-rusca": pair_tr_ceviriTurkceRusca as unknown as FeatureContent,
  "uk/perekladach-z-ukrainskoi-na-anhliysku": pair_uk_perekladachZUkrainskoiNaAnhliysku as unknown as FeatureContent,
  "uk/perekladach-z-ukrainskoi-na-chesku": pair_uk_perekladachZUkrainskoiNaChesku as unknown as FeatureContent,
  "uk/perekladach-z-ukrainskoi-na-ispansku": pair_uk_perekladachZUkrainskoiNaIspansku as unknown as FeatureContent,
  "uk/perekladach-z-ukrainskoi-na-italiysku": pair_uk_perekladachZUkrainskoiNaItaliysku as unknown as FeatureContent,
  "uk/perekladach-z-ukrainskoi-na-nimetsku": pair_uk_perekladachZUkrainskoiNaNimetsku as unknown as FeatureContent,
  "uk/perekladach-z-ukrainskoi-na-polsku": pair_uk_perekladachZUkrainskoiNaPolsku as unknown as FeatureContent,
  "uk/perekladach-z-ukrainskoi-na-rosiysku": pair_uk_perekladachZUkrainskoiNaRosiysku as unknown as FeatureContent,
  "zh/fanyi-zhongwen-ewen": pair_zh_fanyiZhongwenEwen as unknown as FeatureContent,
  "zh/fanyi-zhongwen-riwen": pair_zh_fanyiZhongwenRiwen as unknown as FeatureContent,
  "zh/fanyi-zhongwen-yingwen": pair_zh_fanyiZhongwenYingwen as unknown as FeatureContent,
};

// Locales whose chrome (and therefore home page) actually exists — the
// rollout gate for static params, sitemap, hreflang and the locale switcher.
export const READY_LOCALES: string[] = ["en","ru","ar","bg","ca","cs","da","de","el","es","et","fa","fi","fr","hr","hu","is","it","ja","ko","lt","lv","nl","no","pl","pt","ro","sk","sl","sr","sv","tr","uk","zh"];
